name: CI/CD
on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - '*'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Configure NuGet
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/Yuman-net/index.json --name GitHub --username and.nik.dev@gmail.com --password ${{ secrets.PKG_SECRET }} --store-password-in-clear-text

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          ./bin/Release
      
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: |
            ./bin/Release
      
      - name: Run tests
        run: dotnet test --no-restore --verbosity normal
      
  pack:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PKG_SECRET }}
  
      - name: Build and push Docker image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./WebApi/Dockerfile
          push: true
          tags: ghcr.io/yuman-net/vacancyservice:latest
          build-args: |
            NUGET_PASS=${{ secrets.PKG_SECRET }}
  
      - name: Push Docker image
        run: |
          docker push ghcr.io/yuman-net/vacancyservice:latest
  
